export const READ_ENTITIES_SUCCESFUL = 'READ_ENTITIES_SUCCESFUL';
export const READ_ENTITIES_PENDING = 'READ_ENTITIES_PENDING';
export const READ_ENTITIES_FAILURE = 'READ_ENTITIES_FAILURE';

export const ADD_ENTITIES_SUCCESFUL = 'ADD_ENTITIES_SUCCESFUL';
export const ADD_ENTITIES_PENDING = 'ADD_ENTITIES_PENDING';
export const ADD_ENTITIES_FAILURE = 'ADD_ENTITIES_FAILURE';

export const UPDATE_ENTITIES_SUCCESFUL = 'UPDATE_ENTITIES_SUCCESFUL';
export const UPDATE_ENTITIES_PENDING = 'UPDATE_ENTITIES_PENDING';
export const UPDATE_ENTITIES_FAILURE = 'UPDATE_ENTITIES_FAILURE';

export const DELETE_ENTITIES_SUCCESFUL = 'DELETE_ENTITIES_SUCCESFUL';
export const DELETE_ENTITIES_FAILURE = 'DELETE_ENTITIES_FAILURE';