
export const READ_APPLICATIONS_SUCCESFUL = 'READ_APPLICATIONS_SUCCESFUL';
export const READ_APPLICATIONS_PENDING = 'READ_APPLICATIONS_PENDING';
export const READ_APPLICATIONS_FAILURE = 'READ_APPLICATIONS_FAILURE';
export const DELETE_APPLICATION_SUCCESFUL = 'DELETE_APPLICATION_SUCCESFUL';
export const DELETE_APPLICATION_FAILURE = 'DELETE_APPLICATION_FAILURE';

export const READ_CUSTOMERS_SUCCESFUL = 'READ_CUSTOMERS_SUCCESFUL';
export const READ_CUSTOMERS_PENDING = 'READ_CUSTOMERS_PENDING';
export const READ_CUSTOMERS_FAILURE = 'READ_CUSTOMERS_FAILURE';

