

//<--------------------- APPLICATIONS ------------------------>
export const READ_APPLICATIONS_SUCCESSFUL = 'READ_APPLICATIONS_SUCCESSFUL';
export const READ_APPLICATIONS_PENDING = 'READ_APPLICATIONS_PENDING';
export const READ_APPLICATIONS_FAILURE = 'READ_APPLICATIONS_FAILURE';

export const CREATE_APPLICATION_SUCCESSFUL = 'CREATE_APPLICATION_SUCCESSFUL';
export const CREATE_APPLICATION_FAILURE = 'CREATE_APPLICATION_FAILURE';

export const UPDATE_APPLICATION_SUCCESSFUL = 'UPDATE_APPLICATION_SUCCESSFUL';
export const UPDATE_APPLICATION_FAILURE = 'UPDATE_APPLICATION_FAILURE';

export const DELETE_APPLICATION_SUCCESSFUL = 'DELETE_APPLICATION_SUCCESSFUL';
export const DELETE_APPLICATION_FAILURE = 'DELETE_APPLICATION_FAILURE';

//<--------------------- CUSTOMERS ------------------------>
export const READ_CUSTOMERS_SUCCESSFUL = 'READ_CUSTOMERS_SUCCESSFUL';
export const READ_CUSTOMERS_PENDING = 'READ_CUSTOMERS_PENDING';
export const READ_CUSTOMERS_FAILURE = 'READ_CUSTOMERS_FAILURE';

export const CREATE_CUSTOMER_SUCCESSFUL = 'CREATE_CUSTOMER_SUCCESSFUL';
export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE';

export const UPDATE_CUSTOMER_SUCCESSFUL = 'UPDATE_CUSTOMER_SUCCESSFUL';
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';

export const DELETE_CUSTOMER_SUCCESSFUL = 'DELETE_CUSTOMER_SUCCESSFUL';
export const DELETE_CUSTOMER_FAILURE = 'DELETE_CUSTOMER_FAILURE';

//<--------------------- ORDERS ------------------------>
export const READ_ORDERS_SUCCESSFUL = 'READ_ORDERS_SUCCESSFUL';
export const READ_ORDERS_PENDING = 'READ_ORDERS_PENDING';
export const READ_ORDERS_FAILURE = 'READ_ORDERS_FAILURE';

//<--------------------- PRODUCTS ------------------------>
export const READ_PRODUCTS_SUCCESSFUL = 'READ_PRODUCTS_SUCCESSFUL';
export const READ_PRODUCTS_PENDING = 'READ_PRODUCTS_PENDING';
export const READ_PRODUCTS_FAILURE = 'READ_PRODUCTS_FAILURE';

//<---------------------ADDRESSES ------------------------>
export const READ_ADDRESSES_SUCCESSFUL = 'READ_ADDRESSES_SUCCESSFUL';
export const READ_ADDRESSES_PENDING = 'READ_ADDRESSES_PENDING';
export const READ_ADDRESSES_FAILURE = 'READ_ADDRESSES_FAILURE';
